---
ID: "fe4c9ec2-ddd8-4979-a7ee-57dae82625a3"
Parent: "e89c95fe-d7e6-4fc3-b732-d9b6aefc7b69"
Template: "c14bf746-030f-4e59-8594-395f6d299e61"
Path: "/sitecore/content/vital-greens/chlorella-detox-capsules/Settings/Shared Sites Settings"
BranchID: "55330bb7-6095-414a-b29b-0042ce8d9331"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{4CAE3F14-39ED-448F-A48C-F7A985A6EB77}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240826T182535Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\justin.vogt@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\justin.vogt@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4e8dbb01-22ec-4b09-b2ac-42c619d3c366"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\justin.vogt@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240826T182535Z
